services:
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "8081:8080"
  myimage:
    image: oluwaseun7/profile:1.0.1